name: CI/CD Workflow

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build the Project
        run: dotnet build WebApplication1/WebApplication1.csproj
      
      - name: Publish Project
        run: dotnet publish WebApplication1/WebApplication1.csproj -o WebApplication1/publishoutput

      - name: Deliver Artifact
        uses: actions/upload-artifact@v3
        with:
          name: razorapptobestaged
          path: output

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: razorapptobestaged

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: WebApplication1/publishoutput
          github_token: ${{ secrets.GITHUB_TOKEN }}



